In [1]:
from keras import Sequential
from keras.layers import Dense, SimpleRNN

In [3]:
model = Sequential()

model.add(SimpleRNN(3, input_shape=(4, 5)))
model.add(Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 3)                 27        
                                                                 
 dense (Dense)               (None, 1)                 4         
                                                                 
Total params: 31
Trainable params: 31
Non-trainable params: 0
_________________________________________________________________


In [8]:
# Weights of first layer (from input)

print(model.get_weights()[0].shape)
model.get_weights()[0]

(5, 3)


array([[ 0.4831068 ,  0.865256  ,  0.22522312],
       [-0.12672412, -0.15429825,  0.57332367],
       [-0.7104261 , -0.21804875,  0.13802487],
       [ 0.04112804,  0.7693619 ,  0.3000216 ],
       [ 0.15775508, -0.8383755 ,  0.15019685]], dtype=float32)

In [10]:
# Weights of first layer (from previous first layer)

print(model.get_weights()[1].shape)
model.get_weights()[1]

(3, 3)


array([[-0.94548297,  0.28749505,  0.15299815],
       [-0.3210871 , -0.7443533 , -0.58552635],
       [-0.05445123, -0.60273093,  0.79608446]], dtype=float32)

In [11]:
# Bias of first layer

print(model.get_weights()[2].shape)
model.get_weights()[2]

(3,)


array([0., 0., 0.], dtype=float32)

In [12]:
# Weights of second layer

print(model.get_weights()[3].shape)
model.get_weights()[3]

(3, 1)


array([[-0.88872015],
       [-0.9614117 ],
       [ 1.0476478 ]], dtype=float32)

In [13]:
# Bias of second layer

print(model.get_weights()[4].shape)
model.get_weights()[4]

(1,)


array([0.], dtype=float32)

In [55]:
import numpy as np

In [56]:
docs = ['random text',
       'nepal nepal',
       'hip hip hurray',
       'nepal is beautiful',
       'nepal is clean',
       'recurrent neural network',
       'convolution neural network',
       'artificial neural network',
       'nvidia makes gpu',
       'gpu is expensive']

In [57]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token="<nothing>")

In [58]:
tokenizer.fit_on_texts(docs)

In [59]:
tokenizer

In [60]:
tokenizer.word_index


{'<nothing>': 1,
 'nepal': 2,
 'is': 3,
 'neural': 4,
 'network': 5,
 'hip': 6,
 'gpu': 7,
 'random': 8,
 'text': 9,
 'hurray': 10,
 'beautiful': 11,
 'clean': 12,
 'recurrent': 13,
 'convolution': 14,
 'artificial': 15,
 'nvidia': 16,
 'makes': 17,
 'expensive': 18}

In [61]:
tokenizer.word_counts

OrderedDict([('random', 1),
             ('text', 1),
             ('nepal', 4),
             ('hip', 2),
             ('hurray', 1),
             ('is', 3),
             ('beautiful', 1),
             ('clean', 1),
             ('recurrent', 1),
             ('neural', 3),
             ('network', 3),
             ('convolution', 1),
             ('artificial', 1),
             ('nvidia', 1),
             ('makes', 1),
             ('gpu', 2),
             ('expensive', 1)])

In [62]:
tokenizer.document_count

10

In [63]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[8, 9],
 [2, 2],
 [6, 6, 10],
 [2, 3, 11],
 [2, 3, 12],
 [13, 4, 5],
 [14, 4, 5],
 [15, 4, 5],
 [16, 17, 7],
 [7, 3, 18]]

In [64]:
from keras.utils import pad_sequences

In [65]:
sequences = pad_sequences(sequences, padding='post')

In [66]:
sequences

array([[ 8,  9,  0],
       [ 2,  2,  0],
       [ 6,  6, 10],
       [ 2,  3, 11],
       [ 2,  3, 12],
       [13,  4,  5],
       [14,  4,  5],
       [15,  4,  5],
       [16, 17,  7],
       [ 7,  3, 18]])

In [87]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense, SimpleRNN, Embedding, Flatten

In [88]:
(X_train, y_train), (X_test, y_test) = imdb.load_data()

In [89]:
X_train[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 22665,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 21631,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 19193,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 10311,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 31050,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 12118,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5

In [90]:
len(X_train[0])

218

In [91]:
X_train = pad_sequences(X_train, padding='post', maxlen=50)
X_test = pad_sequences(X_test, padding='post', maxlen=50)

In [92]:
X_train[0]

array([2071,   56,   26,  141,    6,  194, 7486,   18,    4,  226,   22,
         21,  134,  476,   26,  480,    5,  144,   30, 5535,   18,   51,
         36,   28,  224,   92,   25,  104,    4,  226,   65,   16,   38,
       1334,   88,   12,   16,  283,    5,   16, 4472,  113,  103,   32,
         15,   16, 5345,   19,  178,   32])

In [53]:
model = Sequential()

model.add(SimpleRNN(32, input_shape=(50, 1), return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 32)                1088      
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 1,121
Trainable params: 1,121
Non-trainable params: 0
_________________________________________________________________


In [54]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Epoch 1/5
782/782 [==============================] - 7s 8ms/step - loss: 0.6938 - accuracy: 0.5014 - val_loss: 0.6939 - val_accuracy: 0.5036
Epoch 2/5
782/782 [==============================] - 6s 8ms/step - loss: 0.6932 - accuracy: 0.5028 - val_loss: 0.6944 - val_accuracy: 0.5044
Epoch 3/5
782/782 [==============================] - 6s 8ms/step - loss: 0.6932 - accuracy: 0.5062 - val_loss: 0.6943 - val_accuracy: 0.5018
Epoch 4/5
782/782 [==============================] - 6s 7ms/step - loss: 0.6930 - accuracy: 0.5097 - val_loss: 0.6937 - val_accuracy: 0.5020
Epoch 5/5
782/782 [==============================] - 6s 7ms/step - loss: 0.6934 - accuracy: 0.5012 - val_loss: 0.6942 - val_accuracy: 0.5028


In [93]:
X_train.shape

(25000, 50)

In [94]:
from keras.layers import Embedding, Flatten

In [95]:
model = Sequential()
model.add(Embedding(25000, 2, input_length=50))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_7 (Embedding)     (None, 50, 2)             50000     
                                                                 
 simple_rnn_3 (SimpleRNN)    (None, 32)                1120      
                                                                 
 dense_3 (Dense)             (None, 1)                 33        
                                                                 
Total params: 51,153
Trainable params: 51,153
Non-trainable params: 0
_________________________________________________________________


In [96]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Epoch 1/5


InvalidArgumentError: Graph execution error:

Detected at node 'sequential_9/embedding_7/embedding_lookup' defined at (most recent call last):
    File "c:\users\dipin\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "c:\users\dipin\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "D:\ML\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
      app.launch_new_instance()
    File "D:\ML\lib\site-packages\traitlets\config\application.py", line 1043, in launch_instance
      app.start()
    File "D:\ML\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
      self.io_loop.start()
    File "D:\ML\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
      self.asyncio_loop.run_forever()
    File "c:\users\dipin\appdata\local\programs\python\python37\lib\asyncio\base_events.py", line 534, in run_forever
      self._run_once()
    File "c:\users\dipin\appdata\local\programs\python\python37\lib\asyncio\base_events.py", line 1771, in _run_once
      handle._run()
    File "c:\users\dipin\appdata\local\programs\python\python37\lib\asyncio\events.py", line 88, in _run
      self._context.run(self._callback, *self._args)
    File "D:\ML\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
      await self.process_one()
    File "D:\ML\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
      await dispatch(*args)
    File "D:\ML\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
      await result
    File "D:\ML\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
      reply_content = await reply_content
    File "D:\ML\lib\site-packages\ipykernel\ipkernel.py", line 387, in do_execute
      cell_id=cell_id,
    File "D:\ML\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
      return super().run_cell(*args, **kwargs)
    File "D:\ML\lib\site-packages\IPython\core\interactiveshell.py", line 2976, in run_cell
      raw_cell, store_history, silent, shell_futures, cell_id
    File "D:\ML\lib\site-packages\IPython\core\interactiveshell.py", line 3030, in _run_cell
      return runner(coro)
    File "D:\ML\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
      coro.send(None)
    File "D:\ML\lib\site-packages\IPython\core\interactiveshell.py", line 3258, in run_cell_async
      interactivity=interactivity, compiler=compiler, result=result)
    File "D:\ML\lib\site-packages\IPython\core\interactiveshell.py", line 3473, in run_ast_nodes
      if (await self.run_code(code, result,  async_=asy)):
    File "D:\ML\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "C:\Users\Dipin\AppData\Local\Temp\ipykernel_9544\2583242906.py", line 2, in <module>
      history = model.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))
    File "D:\ML\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "D:\ML\lib\site-packages\keras\engine\training.py", line 1650, in fit
      tmp_logs = self.train_function(iterator)
    File "D:\ML\lib\site-packages\keras\engine\training.py", line 1249, in train_function
      return step_function(self, iterator)
    File "D:\ML\lib\site-packages\keras\engine\training.py", line 1233, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "D:\ML\lib\site-packages\keras\engine\training.py", line 1222, in run_step
      outputs = model.train_step(data)
    File "D:\ML\lib\site-packages\keras\engine\training.py", line 1023, in train_step
      y_pred = self(x, training=True)
    File "D:\ML\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "D:\ML\lib\site-packages\keras\engine\training.py", line 561, in __call__
      return super().__call__(*args, **kwargs)
    File "D:\ML\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "D:\ML\lib\site-packages\keras\engine\base_layer.py", line 1132, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "D:\ML\lib\site-packages\keras\utils\traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "D:\ML\lib\site-packages\keras\engine\sequential.py", line 413, in call
      return super().call(inputs, training=training, mask=mask)
    File "D:\ML\lib\site-packages\keras\engine\functional.py", line 511, in call
      return self._run_internal_graph(inputs, training=training, mask=mask)
    File "D:\ML\lib\site-packages\keras\engine\functional.py", line 668, in _run_internal_graph
      outputs = node.layer(*args, **kwargs)
    File "D:\ML\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "D:\ML\lib\site-packages\keras\engine\base_layer.py", line 1132, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "D:\ML\lib\site-packages\keras\utils\traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "D:\ML\lib\site-packages\keras\layers\core\embedding.py", line 208, in call
      out = tf.nn.embedding_lookup(self.embeddings, inputs)
Node: 'sequential_9/embedding_7/embedding_lookup'
indices[1,2] = 50247 is not in [0, 25000)
	 [[{{node sequential_9/embedding_7/embedding_lookup}}]] [Op:__inference_train_function_42437]